import type { CareerProps } from '../types/careers';

export const CAREERS: CareerProps[] = [
  {
    position: 'Software Engineer',
    company: 'Ayola',
    logo: '/images/careers/ayola.png',
    location: 'Jakarta Selatan',
    location_type: 'Remote',
    type: 'Fulltime',
    start_date: '2024-01',
    end_date: '',
    industry: 'SaSS',
    link: 'https://www.ayola.co/',
  },
  {
    position: 'Software Engineer Intern',
    company: 'eFishery',
    logo: '/images/careers/eFishery.png',
    location: 'Bandung',
    location_type: 'Remote',
    type: 'Fulltime',
    start_date: '2024-01',
    end_date: '2024-04',
    industry: 'Startup Aqua-Tech',
    link: 'https://efishery.com/',
  },
  {
    position: 'Documentation Engineer Intern',
    company: 'eFishery',
    logo: '/images/careers/eFishery.png',
    location: 'Bandung',
    location_type: 'Remote',
    type: 'Fulltime',
    start_date: '2023-10',
    end_date: '2024-01',
    industry: 'Startup Aqua-Tech',
    link: 'https://efishery.com/',
  },
  {
    position: 'Information Technology Specialist',
    company: 'IndigoHub Makassar',
    logo: '/images/careers/indigo.png',
    location: 'Makassar',
    location_type: 'Onsite',
    type: 'Fulltime',
    start_date: '2022-09',
    end_date: '2022-11',
    industry: 'Startup Incubator',
    link: 'https://www.linkedin.com/company/indigohubmks/about/',
  },
  {
    position: 'Freelance Software Engineer',
    company: 'Freelance',
    logo: '/images/careers/freelance.png',
    location: 'Makassar',
    location_type: 'Remote',
    type: 'Freelance',
    start_date: '2021-9',
    end_date: null,
    industry: '',
    link: 'https://fihaa.my.id/projects',
  },
];
