import { CareerProps } from "../types/careers";

export const CAREERS: CareerProps[] = [
  {
    position: "Freelance Software Developer",
    company: "Freelance",
    logo: "/images/careers/freelance.png",
    location: "Makassar",
    location_type: "Remote",
    type: "Freelance",
    start_date: "2021-9",
    end_date: null,
    industry: "",
    link: "https://fihaa.my.id/projects",
  },
  {
    position: "Documentation Engineer Intern",
    company: "eFishery",
    logo: "/images/careers/eFishery.png",
    location: "Bandung",
    location_type: "Remote",
    type: "Fulltime",
    start_date: "2023-10",
    end_date: null,
    industry: "startup Aqua-Tech",
    link: "https://efishery.com/",
  },
  {
    position: "Information Technology Specialist",
    company: "IndigoHub Makassar",
    logo: "/images/careers/indigo.png",
    location: "Makassar",
    location_type: "Onsite",
    type: "Fulltime",
    start_date: "2022-09",
    end_date: "2022-11",
    industry: "startup incubator",
    link: "https://www.linkedin.com/company/indigohubmks/about/",
  },
];
